- name: setup git
  portage: name=dev-vcs/git state=present

- name: setup etckeeper
  portage: name=etckeeper state=present

- name: check if a repo is initialized already
  shell: cd /etc && git status
  ignore_errors: True
  changed_when: False
  register: result

- name: configure user email in git
  command: git config --global user.email "{{ git_user_email }}"
  when: result|failed # noqa 303

- name: configure user name in git
  command: git config --global user.name "{{ git_user_name }}"
  when: result|failed # noqa 303

- name: init etckeeper repo
  shell: etckeeper init && etckeeper commit "Initial commit"
  when: result|failed

- name: add daily autocommit
  template: src=daily-etckeeper dest=/etc/cron.daily/etckeeper mode=0755
